name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  fsrs: ^2.0.1
  kuromoji: ^1.0.2
  logger: ^2.6.1
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  sqlite3: ^2.9.0
  sqflite_common_ffi:
  path: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi:
  path: 

flutter:
  uses-material-design: true

  assets:
   - assets/dictionary.db